#### Этап A. Работа с форматами данных.

1. Прочитайте items.csv, items.json и items.xml. CSV необходимо прочитать как минимум одним способом через pandas, JSON — с разбором структуры Python, XML — через xml.etree.ElementTree.

In [51]:
import pandas as pd


items_csv = pd.read_csv('data/raw/items.csv')
items_csv.head(2)

    id             name      category    value           updated_at active
0  1.0    Laptop Pro 14   Electronics  1299,99  2025-03-10T09:00:00    yes
1  2.0   Wireless Mouse  electronics      24.5     11.03.2025 10:30      1

In [52]:
import json

with open('data/raw/items.json', 'r') as f:
    items_json = json.load(f)

items_json

{'items': [{'id': 5,
   'name': 'Data Science Handbook',
   'category': 'Books',
   'value': 52.0,
   'updated_at': '2025-04-01T08:45:00',
   'active': True},
  {'id': 6,
   'name': 'Desk Lamp',
   'category': 'Home',
   'value': '19.99',
   'updated_at': '2025-04-02T14:20:00',
   'active': 'true'},
  {'id': 7,
   'name': 'Coffee Grinder',
   'category': 'Home',
   'value': 32.0,
   'updated_at': '2025-03-14T16:10:00',
   'active': True},
  {'id': 8,
   'name': 'Office Chair',
   'category': 'Home',
   'value': 149,
   'updated_at': 1743759000,
   'active': 1},
  {'id': 9,
   'name': 'Building Blocks Set',
   'category': 'toys',
   'value': 27.99,
   'updated_at': '2025-04-20T13:00:00',
   'active': True},
  {'id': 10,
   'name': 'Puzzle 1000',
   'category': 'Toys',
   'value': '14.5',
   'updated_at': '06.05.2025 15:40',
   'active': True}]}

In [53]:
items_json = pd.DataFrame(items_json['items'])
items_json.head(2)

   id                   name category  value           updated_at active
0   5  Data Science Handbook    Books   52.0  2025-04-01T08:45:00   True
1   6              Desk Lamp     Home  19.99  2025-04-02T14:20:00   true

In [54]:
from xml.etree import ElementTree as ET

items_xml = ET.parse('data/raw/items.xml')
for child in items_xml.getroot():
    for subchild in child:
        print(subchild.tag, subchild.text)

id 3
name USB-C Hub
category electronics
value None
updated_at 2025-02-10T11:15:00
active true
id 9
name Building Blocks Set
category Toys
value 29.99
updated_at 2025-05-05 13:00
active true
id 10
name Puzzle 1000
category Toys
value 14.50
updated_at 2025-05-06T15:40:00
active 1
id 11
name Chess Board
category Toys
value 22.0
updated_at 2025/05/07 10:05
active false
id 12
name RC Car
category Toys
value 59,9
updated_at 08.05.2025 17:25
active yes

In [55]:
items_xml = pd.DataFrame([{subchild.tag: subchild.text for subchild in child} for child in items_xml.getroot()])
items_xml.head(2)

  id                 name     category  value           updated_at active
0  3            USB-C Hub  electronics    NaN  2025-02-10T11:15:00   true
1  9  Building Blocks Set         Toys  29.99     2025-05-05 13:00   true

2. Для каждого источника выведите:
- количество записей

In [12]:
print(f'Количество записей в items_csv: {items_csv.shape[0]}')

Количество записей в items_csv: 9

In [43]:
print('Количество записей в items_json:', items_json.shape[0])

Количество записей в items_json: 6

In [44]:
print(f'Количество записей в items_xml: {items_xml.shape[0]}')

Количество записей в items_xml: 5

- список столбцов;

In [25]:
list(items_csv.columns)

['id', 'name', 'category', 'value', 'updated_at', 'active']

In [45]:
list(items_json.columns)

['id', 'name', 'category', 'value', 'updated_at', 'active']

In [46]:
list(items_xml.columns)

['id', 'name', 'category', 'value', 'updated_at', 'active']

- типы данных;

In [47]:
items_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          8 non-null      float64
 1   name        9 non-null      str
 2   category    9 non-null      str
 3   value       9 non-null      str
 4   updated_at  9 non-null      str
 5   active      9 non-null      str
dtypes: float64(1), str(5)
memory usage: 564.0 bytes

In [48]:
items_json.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          6 non-null      int64
 1   name        6 non-null      str
 2   category    6 non-null      str
 3   value       6 non-null      object
 4   updated_at  6 non-null      object
 5   active      6 non-null      object
dtypes: int64(1), object(3), str(2)
memory usage: 420.0+ bytes

In [49]:
items_xml.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          5 non-null      str
 1   name        5 non-null      str
 2   category    5 non-null      str
 3   value       4 non-null      str
 4   updated_at  5 non-null      str
 5   active      5 non-null      str
dtypes: str(6)
memory usage: 372.0 bytes

- количество пропущенных значений;

In [39]:
items_csv.isna().sum()

id            1
name          0
category      0
value         0
updated_at    0
active        0
dtype: int64

In [50]:
items_json.isna().sum()

id            0
name          0
category      0
value         0
updated_at    0
active        0
dtype: int64

In [51]:
items_xml.isna().sum()

id            0
name          0
category      0
value         1
updated_at    0
active        0
dtype: int64

- количество повторяющихся id.

In [ ]:
id_counts = items_csv['id'].value_counts()
duplicates = id_counts[id_counts > 1]

if duplicates.empty:
    print('Нет дубликатов в столбце id')
else:
    for idx, count in duplicates.items():
        print(f'id {idx} встречается {count} раза')

id 2.0 встречается 2 раза

In [60]:
id_counts = items_json['id'].value_counts()
duplicates = id_counts[id_counts > 1]

if duplicates.empty:
    print('Нет дубликатов в столбце id')
else:
    for idx, count in duplicates.items():
        print(f'id {idx} встречается {count} раза')

Нет дубликатов в столбце id

In [61]:
id_counts = items_xml['id'].value_counts()
duplicates = id_counts[id_counts > 1]

if duplicates.empty:
    print('Нет дубликатов в столбце id')
else:
    for idx, count in duplicates.items():
        print(f'id {idx} встречается {count} раза')

Нет дубликатов в столбце id

Напишите функцию `def normalize_items(df)`, которая приводит набор к единой схеме: преобразует id, value, updated_at, active, нормализует текстовые категории и удаляет полные дубликаты.

In [62]:
items_csv.columns

Index(['id', 'name', 'category', 'value', 'updated_at', 'active'], dtype='str')

In [56]:
def normalize_items(df):
    df = df.copy()
    df['id'] = pd.to_numeric(df['id'], errors='coerce').astype('Int64')
    
    df['value'] = df['value'].astype(str).str.replace(',', '.')
    df['value'] = pd.to_numeric(df['value'], errors='coerce')
    
    df['updated_at'] = pd.to_datetime(
        df['updated_at'], format='mixed', errors='coerce'
        )
    
    clean_active = (
        df['active'].astype(str).str.strip().str.lower().str.replace('.0', '', regex=False)
    )
    df['active'] = clean_active.map(
        {'true': True, 'yes': True, '1': True, 'да': True,
        'false': False, 'no': False, '0': False, 'нет': False}
        ).fillna(False)

    df['name'] = df['name'].str.strip().str.lower()
    df['category'] = df['category'].str.strip().str.lower()

    df = df.drop_duplicates()
    df = df.dropna(subset=['id'])

    return df

In [57]:
csv_normalized = normalize_items(items_csv)
json_normalized = normalize_items(items_json)
xml_normalized = normalize_items(items_xml)

Объедините три файла в один DataFrame.

In [102]:
df = pd.concat([csv_normalized, json_normalized, xml_normalized], ignore_index=True)
df.head()

   id             name     category    value          updated_at  active
0   1    laptop pro 14  electronics  1299.99 2025-03-10 09:00:00    True
1   2   wireless mouse  electronics    24.50 2025-11-03 10:30:00    True
2   2   wireless mouse  electronics    24.50 2025-03-11 10:30:00    True
3   3        usb-c hub  electronics    39.00 2025-03-12 11:15:00   False
4   4  python cookbook        books    45.90 2025-03-13 12:00:00    True

Проверьте уникальность id. Если одинаковый идентификатор встречается в нескольких источниках, явно опишите выбранное правило разрешения конфликта.

In [103]:
id_counts = df['id'].value_counts()
duplicates = id_counts[id_counts > 1]

if duplicates.empty:
    print('Нет дубликатов в столбце id')
else:
    for idx, count in duplicates.items():
        print(f'id {idx} встречается {count} раза')

id 2 встречается 2 раза
id 3 встречается 2 раза
id 5 встречается 2 раза
id 6 встречается 2 раза
id 7 встречается 2 раза
id 9 встречается 2 раза
id 10 встречается 2 раза

In [104]:
# оставляем строку с поздней датой
df = df.sort_values(by=['id', 'updated_at'], ascending=True, na_position='first')
df = df.drop_duplicates(subset='id', keep='last').reset_index(drop=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          12 non-null     Int64
 1   name        12 non-null     str
 2   category    12 non-null     str
 3   value       12 non-null     float64
 4   updated_at  12 non-null     datetime64[ns]
 5   active      12 non-null     bool
dtypes: Int64(1), bool(1), datetime64[ns](1), float64(1), str(2)
memory usage: 636.0 bytes

Сохраните нормализованный результат как:
```
data/processed/items_normalized.csv
data/processed/items_normalized.json
data/processed/items_normalized.xml
```

In [108]:
df.to_csv('data/processed/normalized_items.csv', index=False)

# ‘records’ : list like [{column -> value}, … , {column -> value}]
df.to_json('data/processed/normalized_items.json', orient='records', indent=4, date_format='iso', date_unit='s', force_ascii=False, default_handler=str)

df.to_xml('data/processed/normalized_items.xml', index=False, root_name='items', row_name='item')

#### Этап B. REST API через Requests.

Запустите собственный локальный backend (можете обратиться к преподавателю за образцом) и средствами Python выполните:

- GET
- POST
- PUT
- PATCH
- DELETE

Для каждого запроса необходимо вывести и сохранить:

- HTTP-метод
- URL
- параметры запроса или тело
- status_code
- Content-Type
- время выполнения
- ответ сервера

In [1]:
import requests
import time
import pandas as pd


base_url = 'http://localhost:8000/api/items/'
results = []

start_time = time.time()
response = requests.get(
    base_url,
    params={},
    timeout=5
)
end_time = time.time()

response.raise_for_status()

In [6]:
response.json()

[{'id': 1,
  'name': 'laptop pro 14',
  'category': 'electronics',
  'value': 1299.99,
  'updated_at': '2025-03-10T09:00:00',
  'active': True},
 {'id': 2,
  'name': 'wireless mouse',
  'category': 'electronics',
  'value': 24.5,
  'updated_at': '2025-11-03T10:30:00',
  'active': True},
 {'id': 3,
  'name': 'usb-c hub',
  'category': 'electronics',
  'value': 39.0,
  'updated_at': '2025-03-12T11:15:00',
  'active': False},
 {'id': 4,
  'name': 'python cookbook',
  'category': 'books',
  'value': 45.9,
  'updated_at': '2025-03-13T12:00:00',
  'active': True},
 {'id': 5,
  'name': 'data science handbook',
  'category': 'books',
  'value': 52.0,
  'updated_at': '2025-04-01T08:45:00',
  'active': True},
 {'id': 6,
  'name': 'desk lamp',
  'category': 'home',
  'value': 19.99,
  'updated_at': '2025-04-02T14:20:00',
  'active': True},
 {'id': 7,
  'name': 'coffee grinder',
  'category': 'home',
  'value': 32.0,
  'updated_at': '2025-03-14T16:10:00',
  'active': True},
 {'id': 8,
  'name': 'ghost item',
  'category': 'books',
  'value': 5.0,
  'updated_at': '2025-01-01T00:00:00',
  'active': True},
 {'id': 9,
  'name': 'building blocks set',
  'category': 'toys',
  'value': 29.99,
  'updated_at': '2025-05-05T13:00:00',
  'active': True},
 {'id': 10,
  'name': 'puzzle 1000',
  'category': 'toys',
  'value': 14.5,
  'updated_at': '2025-06-05T15:40:00',
  'active': True},
 {'id': 11,
  'name': 'chess board',
  'category': 'toys',
  'value': 22.0,
  'updated_at': '2025-05-07T10:05:00',
  'active': False},
 {'id': 12,
  'name': 'rc car',
  'category': 'toys',
  'value': 59.9,
  'updated_at': '2025-08-05T17:25:00',
  'active': True}]

In [7]:
results.append({
    'method': response.request.method,
    'url': base_url,
    'params/body': response.request.body or response.request.url.split('?', 1)[1] if '?' in response.request.url else None,
    'status_code': response.status_code,
    'response_time': end_time - start_time,
    'response_data': response.json()
})

Надо создать:

- одну новую запись методом POST;

In [10]:
item = {
    'id': 200,
    'name': 'New Item',
    'value': 99.99,
    'category': 'New Category',
    'active': True,
    'updated_at': '2024-06-01T12:00:00Z'
}

start_time = time.time()
response = requests.post(
    base_url,
    json=item,
    timeout=5
)
end_time = time.time()

response.raise_for_status()
response.json()

{'id': 200,
 'name': 'New Item',
 'category': 'New Category',
 'value': 99.99,
 'updated_at': '2024-06-01T12:00:00Z',
 'active': True}

In [11]:
results.append({
    'method': response.request.method,
    'url': base_url,
    'params/body': response.request.body or response.request.url.split('?', 1)[1] if '?' in response.request.url else None,
    'status_code': response.status_code,
    'response_time': end_time - start_time,
    'response_data': response.json()
})

- полностью изменить ее методом PUT;

In [13]:
put_item = {
    'id': 200,
    'name': 'Updated Item',
    'value': 149.99,
    'category': 'Updated Category',
    'active': False,
    'updated_at': '2024-06-02T12:00:00Z'
}

start_time = time.time()
response = requests.put(
    url=f'{base_url}{put_item["id"]}/',
    json=put_item,
    timeout=5
)
end_time = time.time()

response.raise_for_status()
response.json()

{'id': 200,
 'name': 'Updated Item',
 'category': 'Updated Category',
 'value': 149.99,
 'updated_at': '2024-06-02T12:00:00Z',
 'active': False}

In [14]:
results.append({
    'method': response.request.method,
    'url': base_url + str(put_item["id"]) + '/',
    'params/body': response.request.body or response.request.url.split('?', 1)[1] if '?' in response.request.url else None,
    'status_code': response.status_code,
    'response_time': end_time - start_time,
    'response_data': response.json()
})

- изменить только одно поле методом PATCH;

In [15]:
patch_field = {
    'value': 10.09
}

start_time = time.time()
response = requests.patch(
    url=f'{base_url}{put_item["id"]}/',
    json=patch_field,
    timeout=5
)
end_time = time.time()

response.raise_for_status()
response.json()

{'id': 200,
 'name': 'Updated Item',
 'category': 'Updated Category',
 'value': 10.09,
 'updated_at': '2024-06-02T12:00:00Z',
 'active': False}

In [16]:
results.append({
    'method': response.request.method,
    'url': base_url + str(put_item["id"]) + '/',
    'params/body': response.request.body or response.request.url.split('?', 1)[1] if '?' in response.request.url else None,
    'status_code': response.status_code,
    'response_time': end_time - start_time,
    'response_data': response.json()
})


- получить измененную запись методом GET;

In [17]:
start_time = time.time()
response = requests.get(
    url=f'{base_url}{put_item["id"]}/',
    timeout=5
)
end_time = time.time()

response.raise_for_status()
response.json()

{'id': 200,
 'name': 'Updated Item',
 'category': 'Updated Category',
 'value': 10.09,
 'updated_at': '2024-06-02T12:00:00Z',
 'active': False}

In [18]:
results.append({
    'method': response.request.method,
    'url': base_url + str(put_item["id"]) + '/',
    'params/body': response.request.body or response.request.url.split('?', 1)[1] if '?' in response.request.url else None,
    'status_code': response.status_code,
    'response_time': end_time - start_time,
    'response_data': response.json()
})

- удалить ее методом DELETE;

In [19]:
start_time = time.time()
response = requests.delete(
    url=f'{base_url}{put_item["id"]}/',
    timeout=5
)
end_time = time.time()

response.raise_for_status()
response.json()

{'id': 200,
 'name': 'Updated Item',
 'category': 'Updated Category',
 'value': 10.09,
 'updated_at': '2024-06-02T12:00:00Z',
 'active': False}

In [20]:
results.append({
    'method': response.request.method,
    'url': base_url + str(put_item["id"]) + '/',
    'params/body': response.request.body or response.request.url.split('?', 1)[1] if '?' in response.request.url else None,
    'status_code': response.status_code,
    'response_time': end_time - start_time,
    'response_data': response.json()
})

- убедиться повторным GET, что ресурс удален.

In [21]:
start_time = time.time()
response = requests.get(
    url=f'{base_url}{put_item["id"]}/',
    timeout=5
)
end_time = time.time()

response.raise_for_status()

HTTPError: 404 Client Error: Not Found for url: http://localhost:8000/api/items/200

In [22]:
results.append({
    'method': response.request.method,
    'url': base_url + str(put_item["id"]) + '/',
    'params/body': response.request.body or response.request.url.split('?', 1)[1] if '?' in response.request.url else None,
    'status_code': response.status_code,
    'response_time': end_time - start_time,
    'response_data': response.json()
})

#### Этап C. Обработка ошибок.

Реализуйте обработку как минимум трех ситуаций:

- несуществующий id;
- ошибка соединения;
- превышение timeout.

Программа не должна завершаться необработанным traceback. Ошибка должна попасть в лог вместе с URL и ее типом. Requests предоставляет единое семейство исключений RequestException, включая ConnectionError, Timeout и HTTP-ошибки.

In [23]:
def send_request(method, url, **kwargs):
    start_time = time.time()

    try:
        response = requests.request(
            method,
            url,
            **kwargs
        )
        response.raise_for_status()

        result = {
            'method': response.request.method,
            'url': url,
            'params/body': kwargs.get('json') or kwargs.get('params'),
            'status_code': response.status_code,
            'response_time': time.time() - start_time,
            'response_data': response.json()
        }

        results.append(result)
        return result

    except requests.exceptions.RequestException as e:
        result = {
            'method': method,
            'url': url,
            'params/body': kwargs.get('json') or kwargs.get('params'),
            'status_code': response.status_code if 'response' in locals() else None,
            'response_time': time.time() - start_time,
            'error': type(e).__name__,
            'response_data': str(e)
        }

        results.append(result)
        return result

In [24]:
send_request(
    'GET',
    base_url + '99999'
)

{'method': 'GET',
 'url': 'http://localhost:8000/api/items/99999',
 'params/body': None,
 'status_code': 404,
 'response_time': 2.049877882003784,
 'error': 'HTTPError',
 'response_data': '404 Client Error: Not Found for url: http://localhost:8000/api/items/99999'}

In [25]:
send_request(
    'GET',
    base_url
)

{'method': 'GET',
 'url': 'http://localhost:8000/api/items/',
 'params/body': None,
 'status_code': None,
 'response_time': 4.089764356613159,
 'error': 'ConnectionError',
 'response_data': 'HTTPConnectionPool(host=\'localhost\', port=8000): Max retries exceeded with url: /api/items/ (Caused by NewConnectionError("HTTPConnection(host=\'localhost\', port=8000): Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение"))'}

In [26]:
send_request(
    'GET',
    base_url,
    timeout=0.0000001
)

{'method': 'GET',
 'url': 'http://localhost:8000/api/items/',
 'params/body': None,
 'status_code': None,
 'response_time': 0.0209200382232666,
 'error': 'ReadTimeout',
 'response_data': "HTTPConnectionPool(host='localhost', port=8000): Read timed out. (read timeout=1e-07)"}

In [28]:
pd.DataFrame(results)

,method,url,params/body,status_code,response_time,response_data,error
0,GET,http://localhost:8000/api/items/,None,200.0,2.152051,"[{'id': 1, 'name': 'laptop pro 14', 'category'...",NaN
1,POST,http://localhost:8000/api/items/,None,200.0,2.072857,"{'id': 200, 'name': 'New Item', 'category': 'N...",NaN
2,PUT,http://localhost:8000/api/items/200/,None,200.0,2.081614,"{'id': 200, 'name': 'Updated Item', 'category'...",NaN
3,PATCH,http://localhost:8000/api/items/200/,None,200.0,2.073599,"{'id': 200, 'name': 'Updated Item', 'category'...",NaN
4,GET,http://localhost:8000/api/items/200/,None,200.0,2.076900,"{'id': 200, 'name': 'Updated Item', 'category'...",NaN
5,DELETE,http://localhost:8000/api/items/200/,None,200.0,2.059180,"{'id': 200, 'name': 'Updated Item', 'category'...",NaN
6,GET,http://localhost:8000/api/items/200/,None,404.0,2.072788,{'detail': 'Item not found'},NaN
7,GET,http://localhost:8000/api/items/99999,None,404.0,2.049878,404 Client Error: Not Found for url: http://lo...,HTTPError
8,GET,http://localhost:8000/api/items/,None,NaN,4.089764,"HTTPConnectionPool(host='localhost', port=8000...",ConnectionError
9,GET,http://localhost:8000/api/items/,None,NaN,0.020920,"HTTPConnectionPool(host='localhost', port=8000...",ReadTimeout

In [27]:
pd.DataFrame(results).to_csv(
    'results/api_log.csv',
    index=False
)

#### Этап D. Selenium и динамическая страница.

Откройте /dynamic с помощью Selenium WebDriver.

Необходимо:

1. запустить браузер из Python;

In [29]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import Select


driver = webdriver.Chrome()


2. перейти на динамическую страницу;

In [30]:
driver.get('http://localhost:8000/dynamic')


3. дождаться появления элемента управления;

In [31]:
button = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.TAG_NAME, 'button'))
)


4. нажать кнопку загрузки;

In [32]:
button.click()


5. дождаться появления строк таблицы;

In [ ]:
WebDriverWait(driver, 10).until(
    EC.presence_of_all_elements_located(
        (By.CSS_SELECTOR, '#items tr')
    )
)


6. применить фильтр по категории;

In [34]:
category_select = Select(
    driver.find_element(By.ID, 'category')
)

category_select.select_by_value('books')
button.click()


7. собрать данные из отображаемой таблицы;

In [45]:
category_select.select_by_value('')
button.click()

WebDriverWait(driver, 10).until(
    EC.presence_of_element_located(
        (By.CSS_SELECTOR, '#items tr')
    )
)

In [46]:
rows = driver.find_elements(
    By.CSS_SELECTOR,
    '#items tr'
)

print(len(rows))
print(rows[0].text)

12
1 laptop pro 14 electronics 1299.99 true


8. преобразовать их в DataFrame;

In [48]:
data = []

for row in rows:
    cells = row.find_elements(By.TAG_NAME, 'td')

    if len(cells) == 5:
        item = {
            'id': int(cells[0].text),
            'name': cells[1].text,
            'category': cells[2].text,
            'value': float(cells[3].text.replace(',', '.')),
            'active': bool(cells[4].text.strip().lower() in ['true'])
        }

        data.append(item)

data = pd.DataFrame(data)
data.head()

   id                   name     category    value  active
0   1          laptop pro 14  electronics  1299.99    True
1   2         wireless mouse  electronics    24.50    True
2   3              usb-c hub  electronics    39.00   False
3   4        python cookbook        books    45.90    True
4   5  data science handbook        books    52.00    True

9. сохранить selenium_items.csv.

In [49]:
data.to_csv(
    'results/selenium_items.csv',
    index=False
)

driver.quit()

#### Этап E. Сравнение способов получения данных.

In [58]:
comparison = []

# CSV / JSON / XML
start_time = time.time()
formats_data = pd.concat(
    [csv_normalized, json_normalized, xml_normalized],
    ignore_index=True
)

formats_data = formats_data.sort_values(
    by=['id', 'updated_at'],
    ascending=True,
    na_position='first'
)

formats_data = formats_data.drop_duplicates(
    subset='id',
    keep='last'
)

format_time = time.time() - start_time

comparison.append({
    'Способ': 'CSV/XML/JSON',
    'Количество записей': len(formats_data),
    'Уникальных id': formats_data['id'].nunique(),
    'Время': round(format_time, 4),
    'Есть ошибки': 'Нет'
})


# REST API
start_time = time.time()
api_error = False

try:
    response = requests.get(
        base_url,
        timeout=5
    )

    response.raise_for_status()
    api_data = response.json()

except requests.exceptions.RequestException as e:
    api_data = []
    api_error = True

api_time = time.time() - start_time

comparison.append({
    'Способ': 'REST API',
    'Количество записей': len(api_data),
    'Уникальных id': len(set(item['id'] for item in api_data)),
    'Время': round(api_time, 4),
    'Есть ошибки': 'Да' if api_error else 'Нет'
})


# Selenium
start_time = time.time()
selenium_error = False
try:
    from selenium import webdriver
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support import expected_conditions as EC
    from selenium.webdriver.support.ui import WebDriverWait, Select

    driver = webdriver.Chrome()
    driver.get('http://localhost:8000/dynamic')
    button = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.TAG_NAME, 'button'))
    )
    button.click()
    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located(
            (By.CSS_SELECTOR, '#items tr')
        )
    )
    rows = driver.find_elements(
        By.CSS_SELECTOR,
        '#items tr'
    )

    selenium_data = []
    for row in rows:
        cells = row.find_elements(By.TAG_NAME, 'td')

        if len(cells) == 5:
            selenium_data.append({
                'id': int(cells[0].text),
                'name': cells[1].text,
                'category': cells[2].text,
                'value': float(cells[3].text.replace(',', '.')),
                'active': cells[4].text.strip().lower() == 'true'
            })

    selenium_data = pd.DataFrame(selenium_data)

except Exception as e:
    selenium_data = pd.DataFrame()
    selenium_error = True
    print('Ошибка Selenium:', type(e).__name__, e)

finally:
    if 'driver' in locals():
        driver.quit()

selenium_time = time.time() - start_time

comparison.append({
    'Способ': 'Selenium',
    'Количество записей': len(selenium_data),
    'Уникальных id': (
        selenium_data['id'].nunique()
        if not selenium_data.empty else 0
    ),
    'Время': round(selenium_time, 4),
    'Есть ошибки': 'Да' if selenium_error else 'Нет'
})

comparison_df = pd.DataFrame(comparison)
comparison_df

         Способ  Количество записей  Уникальных id   Время Есть ошибки
0  CSV/XML/JSON                  12             12  0.0176         Нет
1      REST API                  12             12  2.0659         Нет
2      Selenium                  12             12  6.5451         Нет